name: Update XML File

on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download XML file
      run: curl -o nbrfxrates.xml https://www.bnr.ro/nbrfxrates.xml

    - name: Update last updated file
      run: echo "$(date)" > last-updated.txt

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Update nbrfxrates.xml and last-updated.txt'
        add: 'nbrfxrates.xml, last-updated.txt'
