name: Update Exchange Rates

on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch: # Allow manual triggers

jobs:
  update-rates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch latest XML data
        run: |
          curl -o nbrfxrates.xml https://www.bnr.ro/nbrfxrates.xml
          date > last-updated.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add nbrfxrates.xml last-updated.txt
          git commit -m "Update exchange rates and last updated timestamp"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
